services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - userprojectdb

  userprojectdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdatadb:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  celery:
    build: .
    restart: unless-stopped
    command: celery -A userproject worker -l info --pool=solo
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - userprojectdb
      - redis

volumes:
  pgdatadb:
  redisdata:

